// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgLWCyjZtGxu9fHvlMYEExUEG4OnwRGDE',
    appId: '1:1083945243814:web:94a3b3e3d1d54351a31067',
    messagingSenderId: '1083945243814',
    projectId: 'cure--helper',
    authDomain: 'cure--helper.firebaseapp.com',
    storageBucket: 'cure--helper.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqiIwwUZsp1qXtRqAi4eU0iaDnyOiM-Ic',
    appId: '1:1083945243814:android:02847ab8b8a0b15fa31067',
    messagingSenderId: '1083945243814',
    projectId: 'cure--helper',
    storageBucket: 'cure--helper.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO1coNIvjWUwQaWNeOzMVK6K5cQ9jsruQ',
    appId: '1:1083945243814:ios:c0bf05fff74266f2a31067',
    messagingSenderId: '1083945243814',
    projectId: 'cure--helper',
    storageBucket: 'cure--helper.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO1coNIvjWUwQaWNeOzMVK6K5cQ9jsruQ',
    appId: '1:1083945243814:ios:197728648e0d4373a31067',
    messagingSenderId: '1083945243814',
    projectId: 'cure--helper',
    storageBucket: 'cure--helper.appspot.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
